### ISSUE TITLE
Execution failed for task ':evotor-integration-library:compileDebugKotlin'

### ISSUE THREAD

**Issue by Mkhab1b** [evotor/react-native-sample#2]
Не могу запустить проект, пишет Execution failed for task ':evotor-integration-library:compileDebugKotlin' . Можете сказать что нужно сдалать, или какую версию использовать и где ???

**Comment by xcam** [comment]
Добрый день
Версия на react-native на текущий момент не поддерживается. Используйте нативную библиотеку https://github.com/evotor/integration-library
Документацию можно найти здесь: https://developer.evotor.ru/docs/doc_java_app_development_prerequisites.html
